name: "My First Python action"
description: "It's just a simple Hello World action."

inputs:
  who:
    description: "Who should we greet?"
    required: true

outputs:
  greeting:
    description: "The greeting that was generated."
    value: ${{ steps.run-python.outputs.greeting }}

runs:
  using: "composite"
  steps:
    - name: Set python3
      uses: actions/setup-python@v5
      with:
        python-version-file: "${{ github.action_path }}/scripts/.python-version"
        cache: "pip"
        cache-dependency-path: "setup.py"

    - name: Install Python packages
      shell: bash
      env:
        GH_ACTION_PATH: ${{ github.action_path }}
      run: |
        pip install -e ${GH_ACTION_PATH}/scripts

    - name: Run Python script
      id: run-python
      shell: bash
      env:
        GH_ACTION_PATH: ${{ github.action_path }}
      run: |
        python3 ${GH_ACTION_PATH}/scripts/entry.py --who "${{ inputs.who }}"
