name: "My First Python action"
description: "It's just a simple Hello World action."

inputs:
  who:
    description: "Who should we greet?"
    required: true

outputs:
  greeting:
    description: "The greeting that was generated."
    value: ${{ steps.run-python.outputs.greeting }}

runs:
  using: "composite"
  steps:
    - name: Set python3
      uses: actions/setup-python@v5
      with:
        python-version-file: "${{ github.action_path }}/.python-version"

    - name: Install Python packages
      shell: bash
      run: pip install -e ${{ github.action_path }}/requirements.txt

    - name: Run Python script
      id: run-python
      shell: bash
      run: python3 ${{ github.action_path }}/greet.py --who "${{ inputs.who }}"
